//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protos/sign_in.proto

package auth;

@kotlin.jvm.JvmSynthetic
inline fun signIn(block: auth.SignInKt.Dsl.() -> Unit): auth.SignInOuterClass.SignIn =
  auth.SignInKt.Dsl._create(auth.SignInOuterClass.SignIn.newBuilder()).apply { block() }._build()
object SignInKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: auth.SignInOuterClass.SignIn.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: auth.SignInOuterClass.SignIn.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): auth.SignInOuterClass.SignIn = _builder.build()

    /**
     * <code>string username = 1;</code>
     */
    var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * <code>string username = 1;</code>
     */
    fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * <code>string password = 2;</code>
     */
    var password: kotlin.String
      @JvmName("getPassword")
      get() = _builder.getPassword()
      @JvmName("setPassword")
      set(value) {
        _builder.setPassword(value)
      }
    /**
     * <code>string password = 2;</code>
     */
    fun clearPassword() {
      _builder.clearPassword()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun auth.SignInOuterClass.SignIn.copy(block: auth.SignInKt.Dsl.() -> Unit): auth.SignInOuterClass.SignIn =
  auth.SignInKt.Dsl._create(this.toBuilder()).apply { block() }._build()
