//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protos/sign_in.proto

package auth;

@kotlin.jvm.JvmSynthetic
inline fun signInResponse(block: auth.SignInResponseKt.Dsl.() -> Unit): auth.SignInOuterClass.SignInResponse =
  auth.SignInResponseKt.Dsl._create(auth.SignInOuterClass.SignInResponse.newBuilder()).apply { block() }._build()
object SignInResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: auth.SignInOuterClass.SignInResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: auth.SignInOuterClass.SignInResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): auth.SignInOuterClass.SignInResponse = _builder.build()

    /**
     * <code>string token = 1;</code>
     */
    var token: kotlin.String
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * <code>string token = 1;</code>
     */
    fun clearToken() {
      _builder.clearToken()
    }

    /**
     * <code>string username = 2;</code>
     */
    var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * <code>string username = 2;</code>
     */
    fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * <code>string email = 3;</code>
     */
    var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * <code>string email = 3;</code>
     */
    fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * <code>string first_name = 4;</code>
     */
    var firstName: kotlin.String
      @JvmName("getFirstName")
      get() = _builder.getFirstName()
      @JvmName("setFirstName")
      set(value) {
        _builder.setFirstName(value)
      }
    /**
     * <code>string first_name = 4;</code>
     */
    fun clearFirstName() {
      _builder.clearFirstName()
    }

    /**
     * <code>int64 age = 6;</code>
     */
    var age: kotlin.Long
      @JvmName("getAge")
      get() = _builder.getAge()
      @JvmName("setAge")
      set(value) {
        _builder.setAge(value)
      }
    /**
     * <code>int64 age = 6;</code>
     */
    fun clearAge() {
      _builder.clearAge()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun auth.SignInOuterClass.SignInResponse.copy(block: auth.SignInResponseKt.Dsl.() -> Unit): auth.SignInOuterClass.SignInResponse =
  auth.SignInResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
